title: A Journey to Germany
description: An account and guide of traveling and living as an ex-pat in Germany.
show_downloads: true
google_analytics: UA-80371043-3
cayman-blog:
  date_format: "%b %-d, %Y"

gems:
  - jekyll-seo-tag

# social:
author: "James Lawton"
image:
twitter:
  username: crossoveranx
#  site:
facebook:
  publisher: james lawton
  profile_id: 
  app_id:

gems:
  - jekyll-sitemap
