title: A Journey to Germany
description: An account and guide of traveling and living as an ex-pat in Germany.
show_downloads: true
cayman-blog:
  date_format: "%b %-d, %Y"


gems:
  - jekyll-analytics

jekyll_analytics:
  GoogleAnalytics:
    id: UA-80371043-3

gems:
  - jekyll-seo-tag

# social:
author: "James Lawton"
image:
twitter:
  username: crossoveranx
#  site:
facebook:
  publisher: james lawton
  profile_id: 
  app_id:
